import { jsx as _jsx, Fragment as _Fragment, jsxs as _jsxs } from "react/jsx-runtime";
import { Composition } from "remotion";
import { ClipComposition } from "./ClipComposition";
import clipCompositions from "./clip-compositions";
// Try to load all clips (generated by preview-all.ts)
let allClips = null;
try {
    const mod = require("./clip-data-all.ts");
    allClips = mod.default;
}
catch {
    // Not available — fall back to single clip mode
}
// Try to load single clip (generated by watch-clip.ts / preview command)
let singleClip = null;
try {
    const mod = require("./clip-data.ts");
    singleClip = mod.default;
}
catch {
    // Not available
}
export const RemotionRoot = () => {
    // All-clips mode: one composition per clip
    if (allClips && Object.keys(allClips).length > 0) {
        return (_jsx(_Fragment, { children: Object.entries(allClips).map(([name, clipData]) => {
                const duration = clipData.clip.endTime - clipData.clip.startTime;
                // Use per-clip component when available, fall back to shared
                const Component = clipCompositions[name] || ClipComposition;
                return (_jsx(Composition, { id: name.replace(/[^a-zA-Z0-9\-\u3000-\u9FFF]/g, "-"), component: Component, durationInFrames: Math.floor(duration * 30), fps: 30, width: 1080, height: 1920, defaultProps: { clipData, clipName: name } }, name));
            }) }));
    }
    // Single-clip mode: original behavior
    if (singleClip) {
        const duration = singleClip.clip.endTime - singleClip.clip.startTime;
        return (_jsx(Composition, { id: "ClipComposition", component: ClipComposition, durationInFrames: Math.floor(duration * 30), fps: 30, width: 1080, height: 1920, defaultProps: { clipData: singleClip } }));
    }
    // No data available
    return (_jsxs("div", { style: {
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            height: "100vh",
            fontSize: 24,
            color: "#f00",
            backgroundColor: "#000",
            textAlign: "center",
            padding: 20,
        }, children: ["No clip data found.", _jsx("br", {}), "Run ", _jsx("code", { children: "bun remotion/preview-all.ts" }), " to preview all clips,", _jsx("br", {}), "or ", _jsx("code", { children: "/preview [name]" }), " for a single clip."] }));
};
//# sourceMappingURL=Root.js.map
