import React from "react";
import { Composition } from "remotion";
import { ClipComposition } from "./ClipComposition";
import type { ClipData } from "../../pipeline/types";

// Try to load all clips (generated by preview-all.ts)
let allClips: Record<string, ClipData> | null = null;
try {
  const mod = require("./clip-data-all.ts") as { default: Record<string, ClipData> };
  allClips = mod.default;
} catch {
  // Not available — fall back to single clip mode
}

// Try to load single clip (generated by watch-clip.ts / preview command)
let singleClip: ClipData | null = null;
try {
  const mod = require("./clip-data.ts") as { default: ClipData };
  singleClip = mod.default;
} catch {
  // Not available
}

export const RemotionRoot: React.FC = () => {
  // All-clips mode: one composition per clip
  if (allClips && Object.keys(allClips).length > 0) {
    return (
      <>
        {Object.entries(allClips).map(([name, clipData]) => {
          const duration = clipData.videoDuration || clipData.clip.endTime;
          return (
            <Composition
              key={name}
              id={name.replace(/[^a-zA-Z0-9\-\u3000-\u9FFF]/g, "-")}
              component={ClipComposition}
              durationInFrames={Math.ceil(duration * 30)}
              fps={30}
              width={1080}
              height={1920}
              defaultProps={{ clipData }}
            />
          );
        })}
      </>
    );
  }

  // Single-clip mode: original behavior
  if (singleClip) {
    const duration = singleClip.videoDuration || singleClip.clip.endTime;
    return (
      <Composition
        id="ClipComposition"
        component={ClipComposition}
        durationInFrames={Math.ceil(duration * 30)}
        fps={30}
        width={1080}
        height={1920}
        defaultProps={{ clipData: singleClip }}
      />
    );
  }

  // No data available
  return (
    <div
      style={{
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        height: "100vh",
        fontSize: 24,
        color: "#f00",
        backgroundColor: "#000",
        textAlign: "center",
        padding: 20,
      }}
    >
      No clip data found.<br/>
      Run <code>bun remotion/preview-all.ts</code> to preview all clips,<br/>
      or <code>/preview [name]</code> for a single clip.
    </div>
  );
};
